<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>bunch</string>
		<string>bunchsnippet</string>
	</array>
	<key>name</key>
	<string>Bunch</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>order matters here, once something matches, it cant be matched by something else</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#interpolation</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#assignment</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>snippets need to be before comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#snippet</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>fragments before comments too</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#fragment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#condition</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#frontmatter</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#dialog</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#hideall</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#appurl</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#file</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#command</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#script</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>appurl</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.negation.bunch</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.modifier.bunch</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.app.bunch</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>comment</key>
							<string>order matters here</string>
						</dict>
						<dict>
							<key>comment</key>
							<string>Default is a special app name</string>
							<key>match</key>
							<string>Default(?=(\s|$))</string>
							<key>name</key>
							<string>storage.modifier.default.bunch</string>
						</dict>
						<dict>
							<key>comment</key>
							<string>_ attempt to hide app after launching</string>
							<key>match</key>
							<string>_(?=(\s|$))</string>
							<key>name</key>
							<string>keyword.operator.modifier.bunch</string>
						</dict>
						<dict>
							<key>comment</key>
							<string>^ forces app to foreground and unhide</string>
							<key>match</key>
							<string>\^(?=(\s|$))</string>
							<key>name</key>
							<string>keyword.operator.modifier.bunch</string>
						</dict>
						<dict>
							<key>comment</key>
							<string>look for specific browsers for urls</string>
							<key>match</key>
							<string>(brave|chrome|edge|firefox|opera|safari|tor|vivaldi):</string>
							<key>name</key>
							<string>keyword.other.browser.bunch</string>
						</dict>
						<dict>
							<key>comment</key>
							<string>look for a delay phrase</string>
							<key>match</key>
							<string>~\d+</string>
							<key>name</key>
							<string>keyword.operator.delay.bunch</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#interpolation</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>comment</key>
			<string>match applications with modifiers, and urls</string>
			<key>match</key>
			<string>( {4}|\t)*(!{1,3})?([|@%]*)\s*(\w.*\n)</string>
		</dict>
		<key>assignment</key>
		<dict>
			<key>comment</key>
			<string>variable assignment outside of front matter</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^\s*(global)?\s*(\w+)\s*(=)\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.bunch</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.bunch</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>match the variable and the = sign</string>
					<key>end</key>
					<string>$</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>```$</string>
							<key>beginCaptures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.heredoc.markdown.bunch</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>markdown syntax multiline string</string>
							<key>end</key>
							<string>^\s*(```)$</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.heredoc.markdown.bunch</string>
								</dict>
							</dict>
							<key>name</key>
							<string>string.quoted.multiline.bunch</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#interpolation</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>begin</key>
							<string>(&lt;&lt;)(\w+)$</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.heredoc.markdown.bunch</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>variable.language.heredoc.bunch</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>heredoc syntax multiline string</string>
							<key>end</key>
							<string>^\s*(\2)$</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>variable.language.heredoc.bunch</string>
								</dict>
							</dict>
							<key>name</key>
							<string>string.quoted.multiline.bunch</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#interpolation</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.bunch</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>assign a value from embedded snippet without a fragment</string>
							<key>match</key>
							<string>(&lt;&lt;)\s*$</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.bunch</string>
								</dict>
								<key>3</key>
								<dict>
									<key>comment</key>
									<string>the name of the embedded fragment, if present</string>
									<key>name</key>
									<string>entity.name.section.fragment.embedded.bunch</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#interpolation</string>
										</dict>
									</array>
								</dict>
							</dict>
							<key>comment</key>
							<string>assign a value from embedded snippet with a fragment name</string>
							<key>match</key>
							<string>(&lt;&lt;#)(\s*)([^?~&lt;#]+)</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.bunch</string>
								</dict>
								<key>2</key>
								<dict>
									<key>comment</key>
									<string>the name of the snippet file</string>
									<key>name</key>
									<string>entity.name.section.snippetfile.bunch</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#interpolation</string>
										</dict>
									</array>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.bunch</string>
								</dict>
								<key>5</key>
								<dict>
									<key>comment</key>
									<string>the fragment name, if present</string>
									<key>name</key>
									<string>entity.name.section.fragment.bunch</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#interpolation</string>
										</dict>
									</array>
								</dict>
							</dict>
							<key>comment</key>
							<string>assign a value with a snippet with a file and a fragment</string>
							<key>match</key>
							<string>(&lt;)\s*([^?~&lt;#]+)((#)([^?~&lt;#]+))?</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#dialog</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#script</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>0</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#interpolation</string>
										</dict>
									</array>
								</dict>
							</dict>
							<key>comment</key>
							<string>bare strings with no quotes</string>
							<key>match</key>
							<string>.*</string>
							<key>name</key>
							<string>string.quoted.single.bunch</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>bool</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.boolean.bunch</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>match boolean operators used in conditionals</string>
			<key>match</key>
			<string>\s(AND|OR|NOT)\s</string>
		</dict>
		<key>command</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.bunch</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.command.left.bunch</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.command.bunch</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#interpolation</string>
						</dict>
					</array>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.command.right.bunch</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>match commands like (dark mode off)</string>
			<key>match</key>
			<string>^( {4}|\t)*([|%!]*)(\()(.*?)(\))</string>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.comment.leading.bunch</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>comment.line.number-sign.bunch</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>comment.line.number-sign.bunch</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>comments starting with #</string>
					<key>match</key>
					<string>(^|\s+)(\#+)(\s.*)$</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.whitespace.comment.leading.bunch</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>comment.line.double-slash.bunch</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>comment.line.double-slash.bunch</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>comments starting with //</string>
					<key>match</key>
					<string>(^|\s+)(/{2,})(.*)$</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.comment.bunch</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>This matches single or multi-line C-style comments like /* my comment */</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.bunch</string>
				</dict>
			</array>
		</dict>
		<key>comparison</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>comparison operators</string>
					<key>match</key>
					<string>\b(weekday|time)\b</string>
					<key>name</key>
					<string>keyword.operator.word.bunch</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b((not )?(has|is)?\s*(not|!)?\s*(parent|child|uuid|file)|(not )?(is|does)( not)?( (running|before|after|open(ing)?|clos(ing|ed)))?|(not|!)|(starts?|begins?|ends?) with|contains?|exists?|(less|greater)( than)?( or equals?( to)?)?|equals?( to)?|[!\^\$\*&lt;=&gt;]+|(yes|no|true|false))\b</string>
					<key>name</key>
					<string>keyword.operator.word.bunch</string>
				</dict>
				<dict>
					<key>match</key>
					<string>==|!=|\^=|!\^=|\$=|!\$=|\*=|!\*=|!</string>
					<key>name</key>
					<string>keyword.operator.word.bunch</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(is )?NOT</string>
					<key>name</key>
					<string>keyword.operator.word.bunch</string>
				</dict>
			</array>
		</dict>
		<key>condition</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.conditional.bunch</string>
						</dict>
						<key>2</key>
						<dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>comment</key>
									<string>the order of these rules matters a lot</string>
								</dict>
								<dict>
									<key>match</key>
									<string>\(</string>
									<key>name</key>
									<string>keyword.operator.group.bunch</string>
								</dict>
								<dict>
									<key>match</key>
									<string>\)</string>
									<key>name</key>
									<string>keyword.operator.group.bunch</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#bool</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#comparison</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#string</string>
								</dict>
								<dict>
									<key>comment</key>
									<string>everything thats left is a variable</string>
									<key>disabled</key>
									<integer>0</integer>
									<key>match</key>
									<string>\w+</string>
									<key>name</key>
									<string>variable.parameter</string>
								</dict>
							</array>
						</dict>
					</dict>
					<key>comment</key>
					<string>match lines with conditionals</string>
					<key>match</key>
					<string>^(?: {4}|\t)*((?:else )?if|else|end)(.*)</string>
				</dict>
			</array>
		</dict>
		<key>dialog</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.bunch</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.bunch</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#interpolation</string>
								</dict>
							</array>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.bunch</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>prompt for text input</string>
					<key>match</key>
					<string>(\?\")(.*)(\")\s*</string>
					<key>name</key>
					<string>meta.dialog.text.bunch</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\?\[</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.dialog.bunch</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>single-line or multi-line query arrays</string>
					<key>end</key>
					<string>(\])\s*((")(.*?)("))?\s*$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.dialog.bunch</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.dialog.bunch</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.bunch</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#interpolation</string>
								</dict>
							</array>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.dialog.bunch</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.dialog.array.bunch</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>,</string>
							<key>name</key>
							<string>keyword.operator.dialog.bunch</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>string.quoted.single.bunch</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.dialog.bunch</string>
								</dict>
								<key>3</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#snippet</string>
										</dict>
									</array>
								</dict>
							</dict>
							<key>match</key>
							<string>\s*((?!,|\n|\]).*?)(?=(,|\n|\]))</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\?\{</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.dialog.bunch</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>single-line or multi-line query dictionariess</string>
					<key>end</key>
					<string>(\})\s*((")(.*?)("))?\s*$</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.dialog.bunch</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.dialog.bunch</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.bunch</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#interpolation</string>
								</dict>
							</array>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.dialog.bunch</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.dialog.dictionary.bunch</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>,</string>
							<key>name</key>
							<string>keyword.operator.dialog.bunch</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>string.quoted.single.bunch</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.dialog.bunch</string>
								</dict>
								<key>3</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#snippet</string>
										</dict>
									</array>
								</dict>
							</dict>
							<key>match</key>
							<string>\s*((?!,|\n|\}).*?)\s*(=&gt;)\s*(.*?)(?=(,|\n|\}))</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.dialog.bunch</string>
						</dict>
						<key>2</key>
						<dict>
							<key>comment</key>
							<string>the file name</string>
							<key>name</key>
							<string>entity.name.function</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#interpolation</string>
								</dict>
							</array>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.dialog.bunch</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.bunch</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#interpolation</string>
								</dict>
							</array>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.dialog.bunch</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>dialogs from external files</string>
					<key>match</key>
					<string>(\?\&lt;)\s*(.*?)\s*((")(.*?)("))?\s*$</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.dialog.bunch</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.quoted.single.bunch</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.dialog.bunch</string>
						</dict>
						<key>4</key>
						<dict>
							<key>comment</key>
							<string>snippet, but we dont include it because there are many snippet options that arent valid here</string>
							<key>name</key>
							<string>entity.name.section</string>
						</dict>
						<key>5</key>
						<dict>
							<key>comment</key>
							<string>this is an app, but we dont include #appurl because there are many otpions which are not valid here</string>
							<key>name</key>
							<string>entity.name.function.app.bunch</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>checkbox array lines</string>
					<key>match</key>
					<string>^(-\[(?:x| |)\])\s+(.*?)(?:\s+(=&gt;)\s+(?:(&lt;&lt;.*?)|(.*?)))?$</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>horizontal rule to separate multiple sets of checkboxes</string>
					<key>match</key>
					<string>^(-{3,})\s*</string>
					<key>name</key>
					<string>keyword.operator.separatecheckboxes.bunch</string>
				</dict>
			</array>
		</dict>
		<key>file</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.file.bunch</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>comment</key>
							<string>close all windows in the app</string>
							<key>match</key>
							<string>XX(?=(\s|$))</string>
							<key>name</key>
							<string>storage.modifier.default.bunch</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.command.bunch</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>storage.type.function.command.bunch</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#interpolation</string>
										</dict>
									</array>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.command.bunch</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>a special command only available on a file line</string>
							<key>match</key>
							<string>(\()(pause|delay) \d+(\))</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.bunch</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>string.quoted.single.bunch</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#typepause</string>
										</dict>
										<dict>
											<key>include</key>
											<string>#interpolation</string>
										</dict>
									</array>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.bunch</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>keystrokes are surrounded by braces</string>
							<key>match</key>
							<string>(\{)(.*)(\})</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.bunch</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>string.quoted.single.bunch</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#typepause</string>
										</dict>
										<dict>
											<key>include</key>
											<string>#interpolation</string>
										</dict>
									</array>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.bunch</string>
								</dict>
							</dict>
							<key>comment</key>
							<string>text to type into the app is surrounded by brackets</string>
							<key>match</key>
							<string>(\[)(.*)(\])</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>variable.parameter</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.bunch</string>
								</dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>string.quoted.single.bunch</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#interpolation</string>
										</dict>
										<dict>
											<key>include</key>
											<string>#comment</string>
										</dict>
									</array>
								</dict>
							</dict>
							<key>comment</key>
							<string>files can look like variable assignments for scripts</string>
							<key>match</key>
							<string>(\w+)\s?(=)\s?(.*)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#interpolation</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#string</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
					</array>
				</dict>
			</dict>
			<key>comment</key>
			<string>files and file like lines that start with a -</string>
			<key>match</key>
			<string>^\s*(-&gt;?)\s(.*)</string>
		</dict>
		<key>fragment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>the marker that separates embedded snippets from the rest of the file</string>
					<key>match</key>
					<string>^___$</string>
					<key>name</key>
					<string>keyword.operator.startembeddedsnippet.bunch</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>entity.name.section</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>fragment header</string>
					<key>match</key>
					<string>^((?:-{2,}|[=&gt;#])[\-=&gt;# ]*)(\[)\s*([^\]]+?)\s*(\])(.*\s*$)</string>
				</dict>
			</array>
		</dict>
		<key>frontmatter</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\A(-{3,})\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.frontmatter.bunch</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>YAML-ish front matter at the top of the file</string>
					<key>end</key>
					<string>^(-{3,})\s*</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.frontmatter.bunch</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.frontmatter.bunch</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>comment</key>
									<string>the key or variable name</string>
									<key>name</key>
									<string>variable.parameter</string>
									<key>patterns</key>
									<array>
										<dict>
											<key>comment</key>
											<string>certain keywords cause bunch to take actions, instead of defining a variable</string>
											<key>match</key>
											<string>(close after|close at|close on|from file|from script|ignore if|ignore unless|ignore|ignores state|menu divider|menu order|only opens|open at|open every|open on|quits apps|run after|run after close|run before|run before close|schedule if|schedule unless|sequence|shortcut|single bunch mode|startup|tags|title prefix|title|toggles)</string>
											<key>name</key>
											<string>storage.type.function</string>
										</dict>
									</array>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.assignment</string>
								</dict>
								<key>3</key>
								<dict>
									<key>patterns</key>
									<array>
										<dict>
											<key>include</key>
											<string>#script</string>
										</dict>
										<dict>
											<key>comment</key>
											<string>bare strings with no quotes</string>
											<key>match</key>
											<string>.*</string>
											<key>name</key>
											<string>string.unquoted.bunch</string>
										</dict>
									</array>
								</dict>
							</dict>
							<key>comment</key>
							<string>match "key: value" </string>
							<key>match</key>
							<string>^(\S[\w ]+)(:)\s*(.*?)$</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>hideall</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>special command to hide all windows</string>
					<key>match</key>
					<string>^@@</string>
					<key>name</key>
					<string>keyword.operator.hideall.bunch</string>
				</dict>
			</array>
		</dict>
		<key>interpolation</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.language.interpolation.left.bunch</string>
						</dict>
						<key>10</key>
						<dict>
							<key>name</key>
							<string>variable.language.interpolation.right.bunch</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>5</key>
						<dict>
							<key>comment</key>
							<string>the slash before a transformation</string>
							<key>name</key>
							<string>keyword.other.variable.transformation.bunch</string>
						</dict>
						<key>6</key>
						<dict>
							<key>comment</key>
							<string>the transformation, i.e. url, shell, raw</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>(raw|shell|typed|url)</string>
									<key>name</key>
									<string>variable.language.transformation.bunch</string>
								</dict>
								<dict>
									<key>match</key>
									<string>.*</string>
									<key>name</key>
									<string>invalid</string>
								</dict>
							</array>
						</dict>
						<key>8</key>
						<dict>
							<key>comment</key>
							<string>the colon to indicate a default value</string>
							<key>name</key>
							<string>keyword.other</string>
						</dict>
						<key>9</key>
						<dict>
							<key>comment</key>
							<string>the default value</string>
							<key>name</key>
							<string>string.unquoted.bunch</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>variable references with their various incantations and transformations</string>
					<key>match</key>
					<string>([\$%]\{)(.+?)(((/)(.*?))|((:)(.*)))?(\})</string>
				</dict>
			</array>
		</dict>
		<key>script</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(!!?)?(\$)\s+(```)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.script.bunch</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.script.bunch</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.script.bunch</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>embedded shell script, markdown syntax</string>
					<key>end</key>
					<string>^```$</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.script.bunch</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.shell</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(!!?)?(\$)\s+(&lt;&lt;)(\w+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.script.bunch</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.script.bunch</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.script.bunch</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>variable.language.heredoc.bunch</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>embedded shell script, heredoc syntax</string>
					<key>end</key>
					<string>^\4$</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>variable.language.heredoc.bunch</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.shell</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(!!?)?(\*)\s+(```)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.script.bunch</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.script.bunch</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.script.bunch</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>embedded applescript, markdown syntax</string>
					<key>end</key>
					<string>^```$</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.script.bunch</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.applescript</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^(!!?)?(\*)\s+(&lt;&lt;)(\w+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.script.bunch</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.script.bunch</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.script.bunch</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>variable.language.heredoc.bunch</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>embedded applescript, heredoc syntax</string>
					<key>end</key>
					<string>^\4$</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>variable.language.heredoc.bunch</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.applescript</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.script.bunch</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.script.bunch</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.bunch</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#interpolation</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#snippet</string>
								</dict>
							</array>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.delay.bunch</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>applescripts and automator workflows</string>
					<key>match</key>
					<string>(!!?)?([*&amp;])\s+(.*?)(\s~\d+)?$</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.script.bunch</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.script.bunch</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string.unquoted.bunch</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#interpolation</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#snippet</string>
								</dict>
							</array>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>storage.type.function</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.delay.bunch</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>shell scripts can have a display clause</string>
					<key>match</key>
					<string>(!!?)?(\$)\s+(.*?)(\(display(?!\w).*\))?(\s~\d+)?$</string>
				</dict>
			</array>
		</dict>
		<key>snippet</key>
		<dict>
			<key>comment</key>
			<string>the order of these patterns is important</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.bunch</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.bunch</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>embedded snippet without a fragment</string>
					<key>match</key>
					<string>( {4}|\t)?(!)?(&lt;&lt;)\s*$</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.bunch</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.bunch</string>
						</dict>
						<key>5</key>
						<dict>
							<key>comment</key>
							<string>the name of the embedded fragment, if present</string>
							<key>name</key>
							<string>entity.name.section.fragment.embedded.bunch</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#interpolation</string>
								</dict>
							</array>
						</dict>
						<key>7</key>
						<dict>
							<key>comment</key>
							<string>the dialog phrase</string>
							<key>name</key>
							<string>string.quoted.double.bunch</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#interpolation</string>
								</dict>
							</array>
						</dict>
						<key>8</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.delay.bunch</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>embedded snippets with a fragment</string>
					<key>match</key>
					<string>( {4}|\t)?(!)?(&lt;&lt;#)(\s*)([^?~&lt;#]+)((\?".*")|(~\d+))?</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>10</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.delay.bunch</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.bunch</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.bunch</string>
						</dict>
						<key>4</key>
						<dict>
							<key>comment</key>
							<string>the name of the snippet file</string>
							<key>name</key>
							<string>entity.name.section.snippetfile.bunch</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#interpolation</string>
								</dict>
							</array>
						</dict>
						<key>6</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.bunch</string>
						</dict>
						<key>7</key>
						<dict>
							<key>comment</key>
							<string>the fragment name, if present</string>
							<key>name</key>
							<string>entity.name.section.fragment.bunch</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#interpolation</string>
								</dict>
							</array>
						</dict>
						<key>9</key>
						<dict>
							<key>comment</key>
							<string>the dialog phrase</string>
							<key>name</key>
							<string>string.quoted.double.bunch</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#interpolation</string>
								</dict>
							</array>
						</dict>
					</dict>
					<key>comment</key>
					<string>a snippet with a file and a fragment</string>
					<key>match</key>
					<string>( {4}|\t)?(!)?(&lt;)\s*([^?~&lt;#]+)((#)([^?~&lt;#]+))?((\?".*")|(~\d+))?</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.bunch</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.bunch</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#interpolation</string>
								</dict>
							</array>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.bunch</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(")(.*?)(")</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.bunch</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.quoted.single.bunch</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>#interpolation</string>
								</dict>
							</array>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.bunch</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(')(.*?)(')</string>
				</dict>
			</array>
		</dict>
		<key>typepause</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>pause sequence in typed strings</string>
					<key>match</key>
					<string>\\\\!\d+</string>
					<key>name</key>
					<string>keyword.operator.bunch</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.bunch</string>
	<key>uuid</key>
	<string>8CEF7241-BE3B-49BF-966C-68DCA9E01C43</string>
</dict>
</plist>
